### ISSUE TITLE
Citation and License about the Data

### ISSUE THREAD

**Issue by huangcq18** [Jason-TsangGL/UFATS-ITSA-RARE#1]
Thank you for your work!

Could you please provide guidance on how to properly cite this work? Additionally, what Creative Commons license applies to the datasets provided?

Thanks!

**Comment by Jason-TsangGL** [comment]
Tsang, J. et al. (2021) Skeletal Muscle Segmentation in Thigh MRI using Convolutional Neural Networks: data from the osteoarthritis initiative. Canadian Arthritis Research Conference. Arthritis Society, Canadian Rheumatology Association, and CIHR-IMHA. 
if you want to cite the conference paper

Tsang, J., Gardea, M., Fang, N., Wong, A., & Toronto General Hospital Research Institute. (2021). UFATS-ITSA-RARE Data Set (1.0.0) [Data set]. Canadian Arthritis Research Conference (CARC), Toronto. Zenodo. https://doi.org/10.5281/zenodo.14030670
for the Dataset itself.


For the Datasets provided in this repo the CC license is **CC BY-SA**

I hope that answers all your questions. Im glad you found my work useful. If you have any other questions feel free to reopen the issue.
